# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'fa8116d5-8e4c-453a-8069-4f669da613a0'
  imageRepository: 'portfolioappslc'
  containerRegistry: 'portolioappslc-hnh6e7etcyg0h9eu.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'
  containerAppName: 'portfolio-app-slc'
  resourceGroup: 'Portfolio-SLC'
  azureSubscription: 'My Learning (538b6b7a-cb91-46ff-a6b9-5ae34c8fff96)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    # Deploy to Azure Container App (Manually added task)
    - task: AzureContainerApps@1
      displayName: 'Deploy to Azure Container App'
      inputs:
        azureSubscription: '$(azureSubscription)'
        containerAppName: '$(containerAppName)'
        resourceGroup: '$(resourceGroup)'
        imageToDeploy: '$(containerRegistry)/$(imageRepository):$(tag)'